# Generated by Django 4.1 on 2022-09-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('brand', models.CharField(max_length=25)),
                ('year', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('cock_type', models.CharField(max_length=25)),
                ('engine_vol', models.FloatField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cars',
            },
        ),
    ]
