# Generated by Django 4.1 on 2022-08-29 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_carmodel_brand_alter_carmodel_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='price',
            field=models.IntegerField(default=5000, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000000)]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2022)]),
        ),
    ]
