# Generated by Django 4.1 on 2022-08-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=25)),
                ('year', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('cock_type', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'cars',
            },
        ),
    ]
