# Generated by Django 4.1 on 2022-08-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_carmodel_engine_vol_alter_carmodel_cock_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='engine_vol',
            field=models.FloatField(),
        ),
    ]
